import json
import requests
from typing import Generator, List, Dict, Any

from app.core.config import GEMINI_API_KEY, MODEL_NAME, TIMEOUT
from app.core.system_prompt import SYSTEM_PROMPT

GEMINI_BASE_URL = "https://generativelanguage.googleapis.com/v1beta/models"


def _convert_messages_to_gemini_format(messages: List[Dict[str, str]]) -> Dict[str, Any]:
    """
    Converts OpenAI/Ollama style messages to Gemini API format.
    """
    contents = []
    
    for msg in messages:
        role = msg.get("role", "user")
        content = msg.get("content", "")
        
        # Map 'assistant' role to 'model' for Gemini
        gemini_role = "model" if role == "assistant" else "user"
        
        if role == "system":
            # Skip system prompt here, handled separately via system_instruction
            continue
            
        contents.append({
            "role": gemini_role,
            "parts": [{"text": content}]
        })
        
    return contents


def generate_response(messages: List[Dict[str, str]]) -> str:
    """
    Generate a complete response using Google Gemini API.
    """
    if not GEMINI_API_KEY:
        return (
            "⚠️ GEMINI_API_KEY is not set.\n\n"
            "To activate First-Son AI for free:\n"
            "1. Get your free API key at https://aistudio.google.com/\n"
            "2. Add `GEMINI_API_KEY=your_key_here` to your backend `.env` file or Render environment variables."
        )

    url = f"{GEMINI_BASE_URL}/{MODEL_NAME}:generateContent?key={GEMINI_API_KEY}"

    gemini_contents = _convert_messages_to_gemini_format(messages)

    payload = {
        "system_instruction": {
            "parts": [{"text": SYSTEM_PROMPT}]
        },
        "contents": gemini_contents,
        "generationConfig": {
            "temperature": 0.7,
            "maxOutputTokens": 2048,
        }
    }

    try:
        response = requests.post(url, json=payload, timeout=TIMEOUT)
        response.raise_for_status()

        data = response.json()
        
        # Extract response text
        candidates = data.get("candidates", [])
        if candidates and "content" in candidates[0]:
            parts = candidates[0]["content"].get("parts", [])
            if parts:
                return parts[0].get("text", "")
                
        return "No response generated by Gemini."

    except requests.exceptions.HTTPError as e:
        print(f"[Gemini API Error] HTTP Error: {e.response.status_code} - {e.response.text}")
        return f"Error communicating with Gemini API: {e.response.text}"
    except Exception as e:
        print(f"[Gemini Service Error] {str(e)}")
        return f"Service Error: {str(e)}"


def generate_stream(messages: List[Dict[str, str]]) -> Generator[str, None, None]:
    """
    Stream response chunks from Google Gemini API.
    """
    if not GEMINI_API_KEY:
        yield (
            "⚠️ GEMINI_API_KEY is not set.\n\n"
            "To activate First-Son AI for free:\n"
            "1. Get your free API key at https://aistudio.google.com/\n"
            "2. Add `GEMINI_API_KEY=your_key_here` to environment variables."
        )
        return

    url = f"{GEMINI_BASE_URL}/{MODEL_NAME}:streamGenerateContent?key={GEMINI_API_KEY}&alt=sse"

    gemini_contents = _convert_messages_to_gemini_format(messages)

    payload = {
        "system_instruction": {
            "parts": [{"text": SYSTEM_PROMPT}]
        },
        "contents": gemini_contents,
        "generationConfig": {
            "temperature": 0.7,
            "maxOutputTokens": 2048,
        }
    }

    try:
        response = requests.post(url, json=payload, stream=True, timeout=TIMEOUT)
        response.raise_for_status()

        for line in response.iter_lines():
            if not line:
                continue

            line_str = line.decode("utf-8")
            if line_str.startswith("data: "):
                data_json = line_str[6:].strip()
                if data_json == "[DONE]":
                    break
                    
                try:
                    data = json.loads(data_json)
                    candidates = data.get("candidates", [])
                    if candidates and "content" in candidates[0]:
                        parts = candidates[0]["content"].get("parts", [])
                        if parts:
                            chunk = parts[0].get("text", "")
                            if chunk:
                                yield chunk
                except json.JSONDecodeError:
                    continue

    except Exception as e:
        print(f"[Gemini Stream Error] {str(e)}")
        yield f"\n[Stream Error: {str(e)}]"


def generate_conversation_title(messages: List[Dict[str, str]]) -> str:
    """
    Generate a short title based on conversation history using Gemini.
    """
    if not GEMINI_API_KEY:
        return "New Chat"

    conversation_text = ""
    for msg in messages:
        role = msg.get("role", "user").capitalize()
        conversation_text += f"{role}: {msg.get('content', '')}\n"

    prompt = f"""
Summarize this conversation into a concise title (2 to 5 words).
Return ONLY the title without quotes or trailing punctuation.

Conversation:
{conversation_text}
"""

    url = f"{GEMINI_BASE_URL}/{MODEL_NAME}:generateContent?key={GEMINI_API_KEY}"

    payload = {
        "system_instruction": {
            "parts": [{"text": "You generate short, accurate 2-5 word titles for conversations."}]
        },
        "contents": [
            {
                "role": "user",
                "parts": [{"text": prompt}]
            }
        ],
        "generationConfig": {
            "temperature": 0.3,
            "maxOutputTokens": 30,
        }
    }

    try:
        response = requests.post(url, json=payload, timeout=30)
        response.raise_for_status()
        data = response.json()
        
        candidates = data.get("candidates", [])
        if candidates and "content" in candidates[0]:
            parts = candidates[0]["content"].get("parts", [])
            if parts:
                raw_title = parts[0].get("text", "").strip()
                clean_title = raw_title.replace('"', '').replace("'", '').rstrip(".!?:")
                words = clean_title.split()
                if len(words) > 5:
                    clean_title = " ".join(words[:5])
                return clean_title if clean_title else "New Chat"
    except Exception as e:
        print(f"[Gemini Title Error] {str(e)}")
        
    return "New Chat"
